/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import com.exoscale.sdk.model.InstanceTarget;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for AttachBlockStorageVolumeToInstanceRequest
 */
public class AttachBlockStorageVolumeToInstanceRequestTest {
    private final AttachBlockStorageVolumeToInstanceRequest model = new AttachBlockStorageVolumeToInstanceRequest();

    /**
     * Model tests for AttachBlockStorageVolumeToInstanceRequest
     */
    @Test
    public void testAttachBlockStorageVolumeToInstanceRequest() {
        // TODO: test AttachBlockStorageVolumeToInstanceRequest
    }

    /**
     * Test the property 'instance'
     */
    @Test
    public void instanceTest() {
        // TODO: test instance
    }

}
