/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for InferenceEngineVersion
 */
public class InferenceEngineVersionTest {
    private final InferenceEngineVersion model = new InferenceEngineVersion();

    /**
     * Model tests for InferenceEngineVersion
     */
    @Test
    public void testInferenceEngineVersion() {
        // TODO: test InferenceEngineVersion
    }

}
