/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import com.exoscale.sdk.model.ApiKeyUsageEntry;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for IngestMeteringRequest
 */
public class IngestMeteringRequestTest {
    private final IngestMeteringRequest model = new IngestMeteringRequest();

    /**
     * Model tests for IngestMeteringRequest
     */
    @Test
    public void testIngestMeteringRequest() {
        // TODO: test IngestMeteringRequest
    }

    /**
     * Test the property 'flushId'
     */
    @Test
    public void flushIdTest() {
        // TODO: test flushId
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'routerId'
     */
    @Test
    public void routerIdTest() {
        // TODO: test routerId
    }

}
