/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for XksKey
 */
public class XksKeyTest {
    private final XksKey model = new XksKey();

    /**
     * Model tests for XksKey
     */
    @Test
    public void testXksKey() {
        // TODO: test XksKey
    }

    /**
     * Test the property 'externalKeyId'
     */
    @Test
    public void externalKeyIdTest() {
        // TODO: test externalKeyId
    }

    /**
     * Test the property 'xksId'
     */
    @Test
    public void xksIdTest() {
        // TODO: test xksId
    }

}
