/*
 * ExoscalePublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.exoscale.apichgva2.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for AccessKeyKnownOperationsResponse type.
 */
public class AccessKeyKnownOperationsResponse {
    private List<AccessKeyOperation> accessKeyOperations;

    /**
     * Default constructor.
     */
    public AccessKeyKnownOperationsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  accessKeyOperations  List of AccessKeyOperation value for accessKeyOperations.
     */
    public AccessKeyKnownOperationsResponse(
            List<AccessKeyOperation> accessKeyOperations) {
        this.accessKeyOperations = accessKeyOperations;
    }

    /**
     * Getter for AccessKeyOperations.
     * @return Returns the List of AccessKeyOperation
     */
    @JsonGetter("access-key-operations")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<AccessKeyOperation> getAccessKeyOperations() {
        return accessKeyOperations;
    }

    /**
     * Setter for AccessKeyOperations.
     * @param accessKeyOperations Value for List of AccessKeyOperation
     */
    @JsonSetter("access-key-operations")
    public void setAccessKeyOperations(List<AccessKeyOperation> accessKeyOperations) {
        this.accessKeyOperations = accessKeyOperations;
    }

    /**
     * Converts this AccessKeyKnownOperationsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessKeyKnownOperationsResponse [" + "accessKeyOperations=" + accessKeyOperations
                + "]";
    }

    /**
     * Builds a new {@link AccessKeyKnownOperationsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessKeyKnownOperationsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accessKeyOperations(getAccessKeyOperations());
        return builder;
    }

    /**
     * Class to build instances of {@link AccessKeyKnownOperationsResponse}.
     */
    public static class Builder {
        private List<AccessKeyOperation> accessKeyOperations;



        /**
         * Setter for accessKeyOperations.
         * @param  accessKeyOperations  List of AccessKeyOperation value for accessKeyOperations.
         * @return Builder
         */
        public Builder accessKeyOperations(List<AccessKeyOperation> accessKeyOperations) {
            this.accessKeyOperations = accessKeyOperations;
            return this;
        }

        /**
         * Builds a new {@link AccessKeyKnownOperationsResponse} object using the set fields.
         * @return {@link AccessKeyKnownOperationsResponse}
         */
        public AccessKeyKnownOperationsResponse build() {
            return new AccessKeyKnownOperationsResponse(accessKeyOperations);
        }
    }
}
