/*
 * ExoscalePublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.exoscale.apichgva2.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DbaasSettingsOpensearchResponse type.
 */
public class DbaasSettingsOpensearchResponse {
    private Settings7 settings;

    /**
     * Default constructor.
     */
    public DbaasSettingsOpensearchResponse() {
    }

    /**
     * Initialization constructor.
     * @param  settings  Settings7 value for settings.
     */
    public DbaasSettingsOpensearchResponse(
            Settings7 settings) {
        this.settings = settings;
    }

    /**
     * Getter for Settings.
     * @return Returns the Settings7
     */
    @JsonGetter("settings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Settings7 getSettings() {
        return settings;
    }

    /**
     * Setter for Settings.
     * @param settings Value for Settings7
     */
    @JsonSetter("settings")
    public void setSettings(Settings7 settings) {
        this.settings = settings;
    }

    /**
     * Converts this DbaasSettingsOpensearchResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DbaasSettingsOpensearchResponse [" + "settings=" + settings + "]";
    }

    /**
     * Builds a new {@link DbaasSettingsOpensearchResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DbaasSettingsOpensearchResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .settings(getSettings());
        return builder;
    }

    /**
     * Class to build instances of {@link DbaasSettingsOpensearchResponse}.
     */
    public static class Builder {
        private Settings7 settings;



        /**
         * Setter for settings.
         * @param  settings  Settings7 value for settings.
         * @return Builder
         */
        public Builder settings(Settings7 settings) {
            this.settings = settings;
            return this;
        }

        /**
         * Builds a new {@link DbaasSettingsOpensearchResponse} object using the set fields.
         * @return {@link DbaasSettingsOpensearchResponse}
         */
        public DbaasSettingsOpensearchResponse build() {
            return new DbaasSettingsOpensearchResponse(settings);
        }
    }
}
