/*
 * ExoscalePublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.exoscale.apichgva2.models;

import com.exoscale.apichgva2.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * This is a model class for LoadBalancer type.
 */
public class LoadBalancer {
    private UUID id;
    private String description;
    private String name;
    private State1Enum state;
    private LocalDateTime createdAt;
    private String ip;
    private List<LoadBalancerService> services;
    private Map<String, String> labels;

    /**
     * Default constructor.
     */
    public LoadBalancer() {
    }

    /**
     * Initialization constructor.
     * @param  id  UUID value for id.
     * @param  description  String value for description.
     * @param  name  String value for name.
     * @param  state  State1Enum value for state.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  ip  String value for ip.
     * @param  services  List of LoadBalancerService value for services.
     * @param  labels  Map of String, value for labels.
     */
    public LoadBalancer(
            UUID id,
            String description,
            String name,
            State1Enum state,
            LocalDateTime createdAt,
            String ip,
            List<LoadBalancerService> services,
            Map<String, String> labels) {
        this.id = id;
        this.description = description;
        this.name = name;
        this.state = state;
        this.createdAt = createdAt;
        this.ip = ip;
        this.services = services;
        this.labels = labels;
    }

    /**
     * Getter for Id.
     * Load Balancer ID
     * @return Returns the UUID
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Load Balancer ID
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for Description.
     * Load Balancer description
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Load Balancer description
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Name.
     * Load Balancer name
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Load Balancer name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for State.
     * Load Balancer state
     * @return Returns the State1Enum
     */
    @JsonGetter("state")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public State1Enum getState() {
        return state;
    }

    /**
     * Setter for State.
     * Load Balancer state
     * @param state Value for State1Enum
     */
    @JsonSetter("state")
    public void setState(State1Enum state) {
        this.state = state;
    }

    /**
     * Getter for CreatedAt.
     * Load Balancer creation date
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created-at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Load Balancer creation date
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("created-at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for Ip.
     * Load Balancer public IP
     * @return Returns the String
     */
    @JsonGetter("ip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIp() {
        return ip;
    }

    /**
     * Setter for Ip.
     * Load Balancer public IP
     * @param ip Value for String
     */
    @JsonSetter("ip")
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * Getter for Services.
     * Load Balancer Services
     * @return Returns the List of LoadBalancerService
     */
    @JsonGetter("services")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LoadBalancerService> getServices() {
        return services;
    }

    /**
     * Setter for Services.
     * Load Balancer Services
     * @param services Value for List of LoadBalancerService
     */
    @JsonSetter("services")
    public void setServices(List<LoadBalancerService> services) {
        this.services = services;
    }

    /**
     * Getter for Labels.
     * @return Returns the Map of String, String
     */
    @JsonGetter("labels")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getLabels() {
        return labels;
    }

    /**
     * Setter for Labels.
     * @param labels Value for Map of String, String
     */
    @JsonSetter("labels")
    public void setLabels(Map<String, String> labels) {
        this.labels = labels;
    }

    /**
     * Converts this LoadBalancer into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LoadBalancer [" + "id=" + id + ", description=" + description + ", name=" + name
                + ", state=" + state + ", createdAt=" + createdAt + ", ip=" + ip + ", services="
                + services + ", labels=" + labels + "]";
    }

    /**
     * Builds a new {@link LoadBalancer.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LoadBalancer.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .description(getDescription())
                .name(getName())
                .state(getState())
                .createdAt(getCreatedAt())
                .ip(getIp())
                .services(getServices())
                .labels(getLabels());
        return builder;
    }

    /**
     * Class to build instances of {@link LoadBalancer}.
     */
    public static class Builder {
        private UUID id;
        private String description;
        private String name;
        private State1Enum state;
        private LocalDateTime createdAt;
        private String ip;
        private List<LoadBalancerService> services;
        private Map<String, String> labels;



        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  State1Enum value for state.
         * @return Builder
         */
        public Builder state(State1Enum state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for ip.
         * @param  ip  String value for ip.
         * @return Builder
         */
        public Builder ip(String ip) {
            this.ip = ip;
            return this;
        }

        /**
         * Setter for services.
         * @param  services  List of LoadBalancerService value for services.
         * @return Builder
         */
        public Builder services(List<LoadBalancerService> services) {
            this.services = services;
            return this;
        }

        /**
         * Setter for labels.
         * @param  labels  Map of String, value for labels.
         * @return Builder
         */
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }

        /**
         * Builds a new {@link LoadBalancer} object using the set fields.
         * @return {@link LoadBalancer}
         */
        public LoadBalancer build() {
            return new LoadBalancer(id, description, name, state, createdAt, ip, services, labels);
        }
    }
}
