/*
 * ExoscalePublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.exoscale.apichgva2.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SosBucketsUsageResponse type.
 */
public class SosBucketsUsageResponse {
    private List<SosBucketUsage> sosBucketsUsage;

    /**
     * Default constructor.
     */
    public SosBucketsUsageResponse() {
    }

    /**
     * Initialization constructor.
     * @param  sosBucketsUsage  List of SosBucketUsage value for sosBucketsUsage.
     */
    public SosBucketsUsageResponse(
            List<SosBucketUsage> sosBucketsUsage) {
        this.sosBucketsUsage = sosBucketsUsage;
    }

    /**
     * Getter for SosBucketsUsage.
     * @return Returns the List of SosBucketUsage
     */
    @JsonGetter("sos-buckets-usage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SosBucketUsage> getSosBucketsUsage() {
        return sosBucketsUsage;
    }

    /**
     * Setter for SosBucketsUsage.
     * @param sosBucketsUsage Value for List of SosBucketUsage
     */
    @JsonSetter("sos-buckets-usage")
    public void setSosBucketsUsage(List<SosBucketUsage> sosBucketsUsage) {
        this.sosBucketsUsage = sosBucketsUsage;
    }

    /**
     * Converts this SosBucketsUsageResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SosBucketsUsageResponse [" + "sosBucketsUsage=" + sosBucketsUsage + "]";
    }

    /**
     * Builds a new {@link SosBucketsUsageResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SosBucketsUsageResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .sosBucketsUsage(getSosBucketsUsage());
        return builder;
    }

    /**
     * Class to build instances of {@link SosBucketsUsageResponse}.
     */
    public static class Builder {
        private List<SosBucketUsage> sosBucketsUsage;



        /**
         * Setter for sosBucketsUsage.
         * @param  sosBucketsUsage  List of SosBucketUsage value for sosBucketsUsage.
         * @return Builder
         */
        public Builder sosBucketsUsage(List<SosBucketUsage> sosBucketsUsage) {
            this.sosBucketsUsage = sosBucketsUsage;
            return this;
        }

        /**
         * Builds a new {@link SosBucketsUsageResponse} object using the set fields.
         * @return {@link SosBucketsUsageResponse}
         */
        public SosBucketsUsageResponse build() {
            return new SosBucketsUsageResponse(sosBucketsUsage);
        }
    }
}
