/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.operations;

import com.exoscale.api.utils.SpeakeasyMetadata;
import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class CreateDbaasKafkaSchemaRegistryAclConfigRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=name")
    private String name;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry;

    public CreateDbaasKafkaSchemaRegistryAclConfigRequest(
            String name,
            com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(dbaasKafkaSchemaRegistryAclEntry, "dbaasKafkaSchemaRegistryAclEntry");
        this.name = name;
        this.dbaasKafkaSchemaRegistryAclEntry = dbaasKafkaSchemaRegistryAclEntry;
    }

    public String name() {
        return name;
    }

    public com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry() {
        return dbaasKafkaSchemaRegistryAclEntry;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreateDbaasKafkaSchemaRegistryAclConfigRequest withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public CreateDbaasKafkaSchemaRegistryAclConfigRequest withDbaasKafkaSchemaRegistryAclEntry(com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry) {
        Utils.checkNotNull(dbaasKafkaSchemaRegistryAclEntry, "dbaasKafkaSchemaRegistryAclEntry");
        this.dbaasKafkaSchemaRegistryAclEntry = dbaasKafkaSchemaRegistryAclEntry;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDbaasKafkaSchemaRegistryAclConfigRequest other = (CreateDbaasKafkaSchemaRegistryAclConfigRequest) o;
        return 
            java.util.Objects.deepEquals(this.name, other.name) &&
            java.util.Objects.deepEquals(this.dbaasKafkaSchemaRegistryAclEntry, other.dbaasKafkaSchemaRegistryAclEntry);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            name,
            dbaasKafkaSchemaRegistryAclEntry);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateDbaasKafkaSchemaRegistryAclConfigRequest.class,
                "name", name,
                "dbaasKafkaSchemaRegistryAclEntry", dbaasKafkaSchemaRegistryAclEntry);
    }
    
    public final static class Builder {
 
        private String name;
 
        private com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        public Builder dbaasKafkaSchemaRegistryAclEntry(com.exoscale.api.models.components.DbaasKafkaSchemaRegistryAclEntry dbaasKafkaSchemaRegistryAclEntry) {
            Utils.checkNotNull(dbaasKafkaSchemaRegistryAclEntry, "dbaasKafkaSchemaRegistryAclEntry");
            this.dbaasKafkaSchemaRegistryAclEntry = dbaasKafkaSchemaRegistryAclEntry;
            return this;
        }
        
        public CreateDbaasKafkaSchemaRegistryAclConfigRequest build() {
            return new CreateDbaasKafkaSchemaRegistryAclConfigRequest(
                name,
                dbaasKafkaSchemaRegistryAclEntry);
        }
    }
}

