/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.operations;

import com.exoscale.api.utils.SpeakeasyMetadata;
import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class DeleteLoadBalancerServiceRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=service-id")
    private String serviceId;

    public DeleteLoadBalancerServiceRequest(
            String id,
            String serviceId) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(serviceId, "serviceId");
        this.id = id;
        this.serviceId = serviceId;
    }

    public String id() {
        return id;
    }

    public String serviceId() {
        return serviceId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public DeleteLoadBalancerServiceRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public DeleteLoadBalancerServiceRequest withServiceId(String serviceId) {
        Utils.checkNotNull(serviceId, "serviceId");
        this.serviceId = serviceId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteLoadBalancerServiceRequest other = (DeleteLoadBalancerServiceRequest) o;
        return 
            java.util.Objects.deepEquals(this.id, other.id) &&
            java.util.Objects.deepEquals(this.serviceId, other.serviceId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            id,
            serviceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteLoadBalancerServiceRequest.class,
                "id", id,
                "serviceId", serviceId);
    }
    
    public final static class Builder {
 
        private String id;
 
        private String serviceId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder serviceId(String serviceId) {
            Utils.checkNotNull(serviceId, "serviceId");
            this.serviceId = serviceId;
            return this;
        }
        
        public DeleteLoadBalancerServiceRequest build() {
            return new DeleteLoadBalancerServiceRequest(
                id,
                serviceId);
        }
    }
}

