/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.operations;

import com.exoscale.api.utils.SpeakeasyMetadata;
import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class GetDnsDomainRecordRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=domain-id")
    private String domainId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=record-id")
    private String recordId;

    public GetDnsDomainRecordRequest(
            String domainId,
            String recordId) {
        Utils.checkNotNull(domainId, "domainId");
        Utils.checkNotNull(recordId, "recordId");
        this.domainId = domainId;
        this.recordId = recordId;
    }

    public String domainId() {
        return domainId;
    }

    public String recordId() {
        return recordId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetDnsDomainRecordRequest withDomainId(String domainId) {
        Utils.checkNotNull(domainId, "domainId");
        this.domainId = domainId;
        return this;
    }

    public GetDnsDomainRecordRequest withRecordId(String recordId) {
        Utils.checkNotNull(recordId, "recordId");
        this.recordId = recordId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetDnsDomainRecordRequest other = (GetDnsDomainRecordRequest) o;
        return 
            java.util.Objects.deepEquals(this.domainId, other.domainId) &&
            java.util.Objects.deepEquals(this.recordId, other.recordId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            domainId,
            recordId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetDnsDomainRecordRequest.class,
                "domainId", domainId,
                "recordId", recordId);
    }
    
    public final static class Builder {
 
        private String domainId;
 
        private String recordId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder domainId(String domainId) {
            Utils.checkNotNull(domainId, "domainId");
            this.domainId = domainId;
            return this;
        }

        public Builder recordId(String recordId) {
            Utils.checkNotNull(recordId, "recordId");
            this.recordId = recordId;
            return this;
        }
        
        public GetDnsDomainRecordRequest build() {
            return new GetDnsDomainRecordRequest(
                domainId,
                recordId);
        }
    }
}

