/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.operations;

import com.exoscale.api.utils.SpeakeasyMetadata;
import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class ResetSksNodepoolFieldRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=sks-nodepool-id")
    private String sksNodepoolId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=field")
    private ResetSksNodepoolFieldPathParamField field;

    public ResetSksNodepoolFieldRequest(
            String id,
            String sksNodepoolId,
            ResetSksNodepoolFieldPathParamField field) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(sksNodepoolId, "sksNodepoolId");
        Utils.checkNotNull(field, "field");
        this.id = id;
        this.sksNodepoolId = sksNodepoolId;
        this.field = field;
    }

    public String id() {
        return id;
    }

    public String sksNodepoolId() {
        return sksNodepoolId;
    }

    public ResetSksNodepoolFieldPathParamField field() {
        return field;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ResetSksNodepoolFieldRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public ResetSksNodepoolFieldRequest withSksNodepoolId(String sksNodepoolId) {
        Utils.checkNotNull(sksNodepoolId, "sksNodepoolId");
        this.sksNodepoolId = sksNodepoolId;
        return this;
    }

    public ResetSksNodepoolFieldRequest withField(ResetSksNodepoolFieldPathParamField field) {
        Utils.checkNotNull(field, "field");
        this.field = field;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResetSksNodepoolFieldRequest other = (ResetSksNodepoolFieldRequest) o;
        return 
            java.util.Objects.deepEquals(this.id, other.id) &&
            java.util.Objects.deepEquals(this.sksNodepoolId, other.sksNodepoolId) &&
            java.util.Objects.deepEquals(this.field, other.field);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            id,
            sksNodepoolId,
            field);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ResetSksNodepoolFieldRequest.class,
                "id", id,
                "sksNodepoolId", sksNodepoolId,
                "field", field);
    }
    
    public final static class Builder {
 
        private String id;
 
        private String sksNodepoolId;
 
        private ResetSksNodepoolFieldPathParamField field;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder sksNodepoolId(String sksNodepoolId) {
            Utils.checkNotNull(sksNodepoolId, "sksNodepoolId");
            this.sksNodepoolId = sksNodepoolId;
            return this;
        }

        public Builder field(ResetSksNodepoolFieldPathParamField field) {
            Utils.checkNotNull(field, "field");
            this.field = field;
            return this;
        }
        
        public ResetSksNodepoolFieldRequest build() {
            return new ResetSksNodepoolFieldRequest(
                id,
                sksNodepoolId,
                field);
        }
    }
}

