/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.operations;

import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class UpdateDbaasServiceGrafanaRequestBody {

    /**
     * Automatic maintenance settings
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance")
    private Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance;

    /**
     * Subscription plan
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("plan")
    private Optional<? extends String> plan;

    /**
     * Service is protected against termination and powering off
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("termination-protection")
    private Optional<? extends Boolean> terminationProtection;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("grafana-settings")
    private Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings;

    /**
     * Allowed CIDR address blocks for incoming connections
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ip-filter")
    private Optional<? extends java.util.List<String>> ipFilter;

    public UpdateDbaasServiceGrafanaRequestBody(
            @JsonProperty("maintenance") Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance,
            @JsonProperty("plan") Optional<? extends String> plan,
            @JsonProperty("termination-protection") Optional<? extends Boolean> terminationProtection,
            @JsonProperty("grafana-settings") Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings,
            @JsonProperty("ip-filter") Optional<? extends java.util.List<String>> ipFilter) {
        Utils.checkNotNull(maintenance, "maintenance");
        Utils.checkNotNull(plan, "plan");
        Utils.checkNotNull(terminationProtection, "terminationProtection");
        Utils.checkNotNull(grafanaSettings, "grafanaSettings");
        Utils.checkNotNull(ipFilter, "ipFilter");
        this.maintenance = maintenance;
        this.plan = plan;
        this.terminationProtection = terminationProtection;
        this.grafanaSettings = grafanaSettings;
        this.ipFilter = ipFilter;
    }

    /**
     * Automatic maintenance settings
     */
    public Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance() {
        return maintenance;
    }

    /**
     * Subscription plan
     */
    public Optional<? extends String> plan() {
        return plan;
    }

    /**
     * Service is protected against termination and powering off
     */
    public Optional<? extends Boolean> terminationProtection() {
        return terminationProtection;
    }

    public Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings() {
        return grafanaSettings;
    }

    /**
     * Allowed CIDR address blocks for incoming connections
     */
    public Optional<? extends java.util.List<String>> ipFilter() {
        return ipFilter;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Automatic maintenance settings
     */
    public UpdateDbaasServiceGrafanaRequestBody withMaintenance(UpdateDbaasServiceGrafanaMaintenance maintenance) {
        Utils.checkNotNull(maintenance, "maintenance");
        this.maintenance = Optional.ofNullable(maintenance);
        return this;
    }

    /**
     * Automatic maintenance settings
     */
    public UpdateDbaasServiceGrafanaRequestBody withMaintenance(Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance) {
        Utils.checkNotNull(maintenance, "maintenance");
        this.maintenance = maintenance;
        return this;
    }

    /**
     * Subscription plan
     */
    public UpdateDbaasServiceGrafanaRequestBody withPlan(String plan) {
        Utils.checkNotNull(plan, "plan");
        this.plan = Optional.ofNullable(plan);
        return this;
    }

    /**
     * Subscription plan
     */
    public UpdateDbaasServiceGrafanaRequestBody withPlan(Optional<? extends String> plan) {
        Utils.checkNotNull(plan, "plan");
        this.plan = plan;
        return this;
    }

    /**
     * Service is protected against termination and powering off
     */
    public UpdateDbaasServiceGrafanaRequestBody withTerminationProtection(boolean terminationProtection) {
        Utils.checkNotNull(terminationProtection, "terminationProtection");
        this.terminationProtection = Optional.ofNullable(terminationProtection);
        return this;
    }

    /**
     * Service is protected against termination and powering off
     */
    public UpdateDbaasServiceGrafanaRequestBody withTerminationProtection(Optional<? extends Boolean> terminationProtection) {
        Utils.checkNotNull(terminationProtection, "terminationProtection");
        this.terminationProtection = terminationProtection;
        return this;
    }

    public UpdateDbaasServiceGrafanaRequestBody withGrafanaSettings(com.exoscale.api.models.components.JsonSchemaGrafana grafanaSettings) {
        Utils.checkNotNull(grafanaSettings, "grafanaSettings");
        this.grafanaSettings = Optional.ofNullable(grafanaSettings);
        return this;
    }

    public UpdateDbaasServiceGrafanaRequestBody withGrafanaSettings(Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings) {
        Utils.checkNotNull(grafanaSettings, "grafanaSettings");
        this.grafanaSettings = grafanaSettings;
        return this;
    }

    /**
     * Allowed CIDR address blocks for incoming connections
     */
    public UpdateDbaasServiceGrafanaRequestBody withIpFilter(java.util.List<String> ipFilter) {
        Utils.checkNotNull(ipFilter, "ipFilter");
        this.ipFilter = Optional.ofNullable(ipFilter);
        return this;
    }

    /**
     * Allowed CIDR address blocks for incoming connections
     */
    public UpdateDbaasServiceGrafanaRequestBody withIpFilter(Optional<? extends java.util.List<String>> ipFilter) {
        Utils.checkNotNull(ipFilter, "ipFilter");
        this.ipFilter = ipFilter;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateDbaasServiceGrafanaRequestBody other = (UpdateDbaasServiceGrafanaRequestBody) o;
        return 
            java.util.Objects.deepEquals(this.maintenance, other.maintenance) &&
            java.util.Objects.deepEquals(this.plan, other.plan) &&
            java.util.Objects.deepEquals(this.terminationProtection, other.terminationProtection) &&
            java.util.Objects.deepEquals(this.grafanaSettings, other.grafanaSettings) &&
            java.util.Objects.deepEquals(this.ipFilter, other.ipFilter);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            maintenance,
            plan,
            terminationProtection,
            grafanaSettings,
            ipFilter);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateDbaasServiceGrafanaRequestBody.class,
                "maintenance", maintenance,
                "plan", plan,
                "terminationProtection", terminationProtection,
                "grafanaSettings", grafanaSettings,
                "ipFilter", ipFilter);
    }
    
    public final static class Builder {
 
        private Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance = Optional.empty();
 
        private Optional<? extends String> plan = Optional.empty();
 
        private Optional<? extends Boolean> terminationProtection = Optional.empty();
 
        private Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings = Optional.empty();
 
        private Optional<? extends java.util.List<String>> ipFilter = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Automatic maintenance settings
         */
        public Builder maintenance(UpdateDbaasServiceGrafanaMaintenance maintenance) {
            Utils.checkNotNull(maintenance, "maintenance");
            this.maintenance = Optional.ofNullable(maintenance);
            return this;
        }

        /**
         * Automatic maintenance settings
         */
        public Builder maintenance(Optional<? extends UpdateDbaasServiceGrafanaMaintenance> maintenance) {
            Utils.checkNotNull(maintenance, "maintenance");
            this.maintenance = maintenance;
            return this;
        }

        /**
         * Subscription plan
         */
        public Builder plan(String plan) {
            Utils.checkNotNull(plan, "plan");
            this.plan = Optional.ofNullable(plan);
            return this;
        }

        /**
         * Subscription plan
         */
        public Builder plan(Optional<? extends String> plan) {
            Utils.checkNotNull(plan, "plan");
            this.plan = plan;
            return this;
        }

        /**
         * Service is protected against termination and powering off
         */
        public Builder terminationProtection(boolean terminationProtection) {
            Utils.checkNotNull(terminationProtection, "terminationProtection");
            this.terminationProtection = Optional.ofNullable(terminationProtection);
            return this;
        }

        /**
         * Service is protected against termination and powering off
         */
        public Builder terminationProtection(Optional<? extends Boolean> terminationProtection) {
            Utils.checkNotNull(terminationProtection, "terminationProtection");
            this.terminationProtection = terminationProtection;
            return this;
        }

        public Builder grafanaSettings(com.exoscale.api.models.components.JsonSchemaGrafana grafanaSettings) {
            Utils.checkNotNull(grafanaSettings, "grafanaSettings");
            this.grafanaSettings = Optional.ofNullable(grafanaSettings);
            return this;
        }

        public Builder grafanaSettings(Optional<? extends com.exoscale.api.models.components.JsonSchemaGrafana> grafanaSettings) {
            Utils.checkNotNull(grafanaSettings, "grafanaSettings");
            this.grafanaSettings = grafanaSettings;
            return this;
        }

        /**
         * Allowed CIDR address blocks for incoming connections
         */
        public Builder ipFilter(java.util.List<String> ipFilter) {
            Utils.checkNotNull(ipFilter, "ipFilter");
            this.ipFilter = Optional.ofNullable(ipFilter);
            return this;
        }

        /**
         * Allowed CIDR address blocks for incoming connections
         */
        public Builder ipFilter(Optional<? extends java.util.List<String>> ipFilter) {
            Utils.checkNotNull(ipFilter, "ipFilter");
            this.ipFilter = ipFilter;
            return this;
        }
        
        public UpdateDbaasServiceGrafanaRequestBody build() {
            return new UpdateDbaasServiceGrafanaRequestBody(
                maintenance,
                plan,
                terminationProtection,
                grafanaSettings,
                ipFilter);
        }
    }
}

