/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DbaasIntegration;
import org.openapitools.client.model.DbaasNodeState;
import org.openapitools.client.model.DbaasServiceBackup;
import org.openapitools.client.model.DbaasServiceGrafanaUsersInner;
import org.openapitools.client.model.DbaasServiceMaintenance;
import org.openapitools.client.model.DbaasServiceMysqlComponentsInner;
import org.openapitools.client.model.DbaasServiceNotification;
import org.openapitools.client.model.DbaasServiceOpensearchConnectionInfo;
import org.openapitools.client.model.EnumServiceState;
import org.openapitools.client.model.JsonSchemaOpensearch;
import org.openapitools.client.model.UpdateDbaasServiceOpensearchRequestIndexPatternsInner;
import org.openapitools.client.model.UpdateDbaasServiceOpensearchRequestIndexTemplate;
import org.openapitools.client.model.UpdateDbaasServiceOpensearchRequestOpensearchDashboards;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DbaasServiceOpensearch
 */
public class DbaasServiceOpensearchTest {
    private final DbaasServiceOpensearch model = new DbaasServiceOpensearch();

    /**
     * Model tests for DbaasServiceOpensearch
     */
    @Test
    public void testDbaasServiceOpensearch() {
        // TODO: test DbaasServiceOpensearch
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'maxIndexCount'
     */
    @Test
    public void maxIndexCountTest() {
        // TODO: test maxIndexCount
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'nodeCount'
     */
    @Test
    public void nodeCountTest() {
        // TODO: test nodeCount
    }

    /**
     * Test the property 'connectionInfo'
     */
    @Test
    public void connectionInfoTest() {
        // TODO: test connectionInfo
    }

    /**
     * Test the property 'nodeCpuCount'
     */
    @Test
    public void nodeCpuCountTest() {
        // TODO: test nodeCpuCount
    }

    /**
     * Test the property 'integrations'
     */
    @Test
    public void integrationsTest() {
        // TODO: test integrations
    }

    /**
     * Test the property 'zone'
     */
    @Test
    public void zoneTest() {
        // TODO: test zone
    }

    /**
     * Test the property 'nodeStates'
     */
    @Test
    public void nodeStatesTest() {
        // TODO: test nodeStates
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'keepIndexRefreshInterval'
     */
    @Test
    public void keepIndexRefreshIntervalTest() {
        // TODO: test keepIndexRefreshInterval
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'ipFilter'
     */
    @Test
    public void ipFilterTest() {
        // TODO: test ipFilter
    }

    /**
     * Test the property 'backups'
     */
    @Test
    public void backupsTest() {
        // TODO: test backups
    }

    /**
     * Test the property 'terminationProtection'
     */
    @Test
    public void terminationProtectionTest() {
        // TODO: test terminationProtection
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'components'
     */
    @Test
    public void componentsTest() {
        // TODO: test components
    }

    /**
     * Test the property 'indexPatterns'
     */
    @Test
    public void indexPatternsTest() {
        // TODO: test indexPatterns
    }

    /**
     * Test the property 'maintenance'
     */
    @Test
    public void maintenanceTest() {
        // TODO: test maintenance
    }

    /**
     * Test the property 'indexTemplate'
     */
    @Test
    public void indexTemplateTest() {
        // TODO: test indexTemplate
    }

    /**
     * Test the property 'diskSize'
     */
    @Test
    public void diskSizeTest() {
        // TODO: test diskSize
    }

    /**
     * Test the property 'nodeMemory'
     */
    @Test
    public void nodeMemoryTest() {
        // TODO: test nodeMemory
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'opensearchSettings'
     */
    @Test
    public void opensearchSettingsTest() {
        // TODO: test opensearchSettings
    }

    /**
     * Test the property 'uriParams'
     */
    @Test
    public void uriParamsTest() {
        // TODO: test uriParams
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

    /**
     * Test the property 'opensearchDashboards'
     */
    @Test
    public void opensearchDashboardsTest() {
        // TODO: test opensearchDashboards
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

}
