/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.exoscale.sdk.model.DbaasDatadogTag;
import com.exoscale.sdk.model.EnumDatadogSite;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DbaasEndpointDatadog
 */
@JsonPropertyOrder({
  DbaasEndpointDatadog.JSON_PROPERTY_API_KEY,
  DbaasEndpointDatadog.JSON_PROPERTY_SITE,
  DbaasEndpointDatadog.JSON_PROPERTY_TAGS,
  DbaasEndpointDatadog.JSON_PROPERTY_DISABLE_CONSUMER_STATS,
  DbaasEndpointDatadog.JSON_PROPERTY_KAFKA_CONSUMER_CHECK_INSTANCES,
  DbaasEndpointDatadog.JSON_PROPERTY_KAFKA_CONSUMER_STATS_TIMEOUT,
  DbaasEndpointDatadog.JSON_PROPERTY_MAX_PARTITION_CONTEXTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class DbaasEndpointDatadog {
  public static final String JSON_PROPERTY_API_KEY = "api-key";
  private String apiKey;

  public static final String JSON_PROPERTY_SITE = "site";
  private EnumDatadogSite site;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<DbaasDatadogTag> tags;

  public static final String JSON_PROPERTY_DISABLE_CONSUMER_STATS = "disable-consumer-stats";
  private Boolean disableConsumerStats;

  public static final String JSON_PROPERTY_KAFKA_CONSUMER_CHECK_INSTANCES = "kafka-consumer-check-instances";
  private Long kafkaConsumerCheckInstances;

  public static final String JSON_PROPERTY_KAFKA_CONSUMER_STATS_TIMEOUT = "kafka-consumer-stats-timeout";
  private Long kafkaConsumerStatsTimeout;

  public static final String JSON_PROPERTY_MAX_PARTITION_CONTEXTS = "max-partition-contexts";
  private Long maxPartitionContexts;

  public DbaasEndpointDatadog() { 
  }

  public DbaasEndpointDatadog apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Datadog API key
   * @return apiKey
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_API_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getApiKey() {
    return apiKey;
  }


  @JsonProperty(JSON_PROPERTY_API_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }


  public DbaasEndpointDatadog site(EnumDatadogSite site) {
    this.site = site;
    return this;
  }

   /**
   * Get site
   * @return site
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EnumDatadogSite getSite() {
    return site;
  }


  @JsonProperty(JSON_PROPERTY_SITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSite(EnumDatadogSite site) {
    this.site = site;
  }


  public DbaasEndpointDatadog tags(List<DbaasDatadogTag> tags) {
    this.tags = tags;
    return this;
  }

  public DbaasEndpointDatadog addTagsItem(DbaasDatadogTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Custom tags provided by user
   * @return tags
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DbaasDatadogTag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<DbaasDatadogTag> tags) {
    this.tags = tags;
  }


  public DbaasEndpointDatadog disableConsumerStats(Boolean disableConsumerStats) {
    this.disableConsumerStats = disableConsumerStats;
    return this;
  }

   /**
   * Disable consumer group metrics
   * @return disableConsumerStats
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISABLE_CONSUMER_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisableConsumerStats() {
    return disableConsumerStats;
  }


  @JsonProperty(JSON_PROPERTY_DISABLE_CONSUMER_STATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisableConsumerStats(Boolean disableConsumerStats) {
    this.disableConsumerStats = disableConsumerStats;
  }


  public DbaasEndpointDatadog kafkaConsumerCheckInstances(Long kafkaConsumerCheckInstances) {
    this.kafkaConsumerCheckInstances = kafkaConsumerCheckInstances;
    return this;
  }

   /**
   * Number of separate instances to fetch kafka consumer statistics with
   * minimum: 1
   * maximum: 100
   * @return kafkaConsumerCheckInstances
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KAFKA_CONSUMER_CHECK_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getKafkaConsumerCheckInstances() {
    return kafkaConsumerCheckInstances;
  }


  @JsonProperty(JSON_PROPERTY_KAFKA_CONSUMER_CHECK_INSTANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKafkaConsumerCheckInstances(Long kafkaConsumerCheckInstances) {
    this.kafkaConsumerCheckInstances = kafkaConsumerCheckInstances;
  }


  public DbaasEndpointDatadog kafkaConsumerStatsTimeout(Long kafkaConsumerStatsTimeout) {
    this.kafkaConsumerStatsTimeout = kafkaConsumerStatsTimeout;
    return this;
  }

   /**
   * Number of seconds that datadog will wait to get consumer statistics from brokers
   * minimum: 2
   * maximum: 300
   * @return kafkaConsumerStatsTimeout
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KAFKA_CONSUMER_STATS_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getKafkaConsumerStatsTimeout() {
    return kafkaConsumerStatsTimeout;
  }


  @JsonProperty(JSON_PROPERTY_KAFKA_CONSUMER_STATS_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKafkaConsumerStatsTimeout(Long kafkaConsumerStatsTimeout) {
    this.kafkaConsumerStatsTimeout = kafkaConsumerStatsTimeout;
  }


  public DbaasEndpointDatadog maxPartitionContexts(Long maxPartitionContexts) {
    this.maxPartitionContexts = maxPartitionContexts;
    return this;
  }

   /**
   * Maximum number of partition contexts to send
   * minimum: 200
   * maximum: 200000
   * @return maxPartitionContexts
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_PARTITION_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMaxPartitionContexts() {
    return maxPartitionContexts;
  }


  @JsonProperty(JSON_PROPERTY_MAX_PARTITION_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPartitionContexts(Long maxPartitionContexts) {
    this.maxPartitionContexts = maxPartitionContexts;
  }


  /**
   * Return true if this dbaas-endpoint-datadog object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DbaasEndpointDatadog dbaasEndpointDatadog = (DbaasEndpointDatadog) o;
    return Objects.equals(this.apiKey, dbaasEndpointDatadog.apiKey) &&
        Objects.equals(this.site, dbaasEndpointDatadog.site) &&
        Objects.equals(this.tags, dbaasEndpointDatadog.tags) &&
        Objects.equals(this.disableConsumerStats, dbaasEndpointDatadog.disableConsumerStats) &&
        Objects.equals(this.kafkaConsumerCheckInstances, dbaasEndpointDatadog.kafkaConsumerCheckInstances) &&
        Objects.equals(this.kafkaConsumerStatsTimeout, dbaasEndpointDatadog.kafkaConsumerStatsTimeout) &&
        Objects.equals(this.maxPartitionContexts, dbaasEndpointDatadog.maxPartitionContexts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, site, tags, disableConsumerStats, kafkaConsumerCheckInstances, kafkaConsumerStatsTimeout, maxPartitionContexts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DbaasEndpointDatadog {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    disableConsumerStats: ").append(toIndentedString(disableConsumerStats)).append("\n");
    sb.append("    kafkaConsumerCheckInstances: ").append(toIndentedString(kafkaConsumerCheckInstances)).append("\n");
    sb.append("    kafkaConsumerStatsTimeout: ").append(toIndentedString(kafkaConsumerStatsTimeout)).append("\n");
    sb.append("    maxPartitionContexts: ").append(toIndentedString(maxPartitionContexts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `api-key` to the URL query string
    if (getApiKey() != null) {
      joiner.add(String.format("%sapi-key%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getApiKey()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `site` to the URL query string
    if (getSite() != null) {
      joiner.add(String.format("%ssite%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSite()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format("%stags%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `disable-consumer-stats` to the URL query string
    if (getDisableConsumerStats() != null) {
      joiner.add(String.format("%sdisable-consumer-stats%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisableConsumerStats()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `kafka-consumer-check-instances` to the URL query string
    if (getKafkaConsumerCheckInstances() != null) {
      joiner.add(String.format("%skafka-consumer-check-instances%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKafkaConsumerCheckInstances()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `kafka-consumer-stats-timeout` to the URL query string
    if (getKafkaConsumerStatsTimeout() != null) {
      joiner.add(String.format("%skafka-consumer-stats-timeout%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getKafkaConsumerStatsTimeout()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `max-partition-contexts` to the URL query string
    if (getMaxPartitionContexts() != null) {
      joiner.add(String.format("%smax-partition-contexts%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaxPartitionContexts()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

