/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GenerateSksKarpenterExoscaleNodeclass200Response
 */
@JsonPropertyOrder({
  GenerateSksKarpenterExoscaleNodeclass200Response.JSON_PROPERTY_EXOSCALE_NODECLASS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class GenerateSksKarpenterExoscaleNodeclass200Response {
  public static final String JSON_PROPERTY_EXOSCALE_NODECLASS = "exoscale-nodeclass";
  private String exoscaleNodeclass;

  public GenerateSksKarpenterExoscaleNodeclass200Response() { 
  }

  public GenerateSksKarpenterExoscaleNodeclass200Response exoscaleNodeclass(String exoscaleNodeclass) {
    this.exoscaleNodeclass = exoscaleNodeclass;
    return this;
  }

   /**
   * Get exoscaleNodeclass
   * @return exoscaleNodeclass
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXOSCALE_NODECLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExoscaleNodeclass() {
    return exoscaleNodeclass;
  }


  @JsonProperty(JSON_PROPERTY_EXOSCALE_NODECLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExoscaleNodeclass(String exoscaleNodeclass) {
    this.exoscaleNodeclass = exoscaleNodeclass;
  }


  /**
   * Return true if this generate_sks_karpenter_exoscale_nodeclass_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateSksKarpenterExoscaleNodeclass200Response generateSksKarpenterExoscaleNodeclass200Response = (GenerateSksKarpenterExoscaleNodeclass200Response) o;
    return Objects.equals(this.exoscaleNodeclass, generateSksKarpenterExoscaleNodeclass200Response.exoscaleNodeclass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exoscaleNodeclass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateSksKarpenterExoscaleNodeclass200Response {\n");
    sb.append("    exoscaleNodeclass: ").append(toIndentedString(exoscaleNodeclass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `exoscale-nodeclass` to the URL query string
    if (getExoscaleNodeclass() != null) {
      joiner.add(String.format("%sexoscale-nodeclass%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExoscaleNodeclass()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

