/*
 * Exoscale API
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Update the models and/or deployments accessible by an AI API key. Omitted properties are left unchanged.
 */
@JsonPropertyOrder({
  UpdateAiApiKeyRequest.JSON_PROPERTY_DEPLOYMENTS,
  UpdateAiApiKeyRequest.JSON_PROPERTY_MODELS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class UpdateAiApiKeyRequest {
  public static final String JSON_PROPERTY_DEPLOYMENTS = "deployments";
  private Set<String> deployments;

  public static final String JSON_PROPERTY_MODELS = "models";
  private Set<String> models;

  public UpdateAiApiKeyRequest() { 
  }

  public UpdateAiApiKeyRequest deployments(Set<String> deployments) {
    this.deployments = deployments;
    return this;
  }

  public UpdateAiApiKeyRequest addDeploymentsItem(String deploymentsItem) {
    if (this.deployments == null) {
      this.deployments = new LinkedHashSet<>();
    }
    this.deployments.add(deploymentsItem);
    return this;
  }

   /**
   * Deployment IDs accepted as input.
   * @return deployments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getDeployments() {
    return deployments;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_DEPLOYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeployments(Set<String> deployments) {
    this.deployments = deployments;
  }


  public UpdateAiApiKeyRequest models(Set<String> models) {
    this.models = models;
    return this;
  }

  public UpdateAiApiKeyRequest addModelsItem(String modelsItem) {
    if (this.models == null) {
      this.models = new LinkedHashSet<>();
    }
    this.models.add(modelsItem);
    return this;
  }

   /**
   * Public model access. An empty array denies access to all public models, [\&quot;all\&quot;] grants access to all public models, otherwise the array is an allowlist of model names.
   * @return models
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getModels() {
    return models;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_MODELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModels(Set<String> models) {
    this.models = models;
  }


  /**
   * Return true if this update-ai-api-key-request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAiApiKeyRequest updateAiApiKeyRequest = (UpdateAiApiKeyRequest) o;
    return Objects.equals(this.deployments, updateAiApiKeyRequest.deployments) &&
        Objects.equals(this.models, updateAiApiKeyRequest.models);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deployments, models);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAiApiKeyRequest {\n");
    sb.append("    deployments: ").append(toIndentedString(deployments)).append("\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deployments` to the URL query string
    if (getDeployments() != null) {
      int i = 0;
      for (String _item : getDeployments()) {
        joiner.add(String.format("%sdeployments%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(_item), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
      i++;
    }

    // add `models` to the URL query string
    if (getModels() != null) {
      int i = 0;
      for (String _item : getModels()) {
        joiner.add(String.format("%smodels%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(_item), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
      i++;
    }

    return joiner.toString();
  }
}

