/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.InlineResponse20032SettingsPg;
import io.swagger.client.model.InlineResponse20032SettingsPgbouncer;
import io.swagger.client.model.InlineResponse20032SettingsPglookout;
import io.swagger.client.model.InlineResponse20032SettingsTimescaledb;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InlineResponse20032Settings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-08T17:23:40.261901+01:00[Europe/Vienna]")

public class InlineResponse20032Settings {
  @JsonProperty("pg")
  private InlineResponse20032SettingsPg pg = null;

  @JsonProperty("pglookout")
  private InlineResponse20032SettingsPglookout pglookout = null;

  @JsonProperty("pgbouncer")
  private InlineResponse20032SettingsPgbouncer pgbouncer = null;

  @JsonProperty("timescaledb")
  private InlineResponse20032SettingsTimescaledb timescaledb = null;

  public InlineResponse20032Settings pg(InlineResponse20032SettingsPg pg) {
    this.pg = pg;
    return this;
  }

   /**
   * Get pg
   * @return pg
  **/
  @Schema(description = "")
  public InlineResponse20032SettingsPg getPg() {
    return pg;
  }

  public void setPg(InlineResponse20032SettingsPg pg) {
    this.pg = pg;
  }

  public InlineResponse20032Settings pglookout(InlineResponse20032SettingsPglookout pglookout) {
    this.pglookout = pglookout;
    return this;
  }

   /**
   * Get pglookout
   * @return pglookout
  **/
  @Schema(description = "")
  public InlineResponse20032SettingsPglookout getPglookout() {
    return pglookout;
  }

  public void setPglookout(InlineResponse20032SettingsPglookout pglookout) {
    this.pglookout = pglookout;
  }

  public InlineResponse20032Settings pgbouncer(InlineResponse20032SettingsPgbouncer pgbouncer) {
    this.pgbouncer = pgbouncer;
    return this;
  }

   /**
   * Get pgbouncer
   * @return pgbouncer
  **/
  @Schema(description = "")
  public InlineResponse20032SettingsPgbouncer getPgbouncer() {
    return pgbouncer;
  }

  public void setPgbouncer(InlineResponse20032SettingsPgbouncer pgbouncer) {
    this.pgbouncer = pgbouncer;
  }

  public InlineResponse20032Settings timescaledb(InlineResponse20032SettingsTimescaledb timescaledb) {
    this.timescaledb = timescaledb;
    return this;
  }

   /**
   * Get timescaledb
   * @return timescaledb
  **/
  @Schema(description = "")
  public InlineResponse20032SettingsTimescaledb getTimescaledb() {
    return timescaledb;
  }

  public void setTimescaledb(InlineResponse20032SettingsTimescaledb timescaledb) {
    this.timescaledb = timescaledb;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20032Settings inlineResponse20032Settings = (InlineResponse20032Settings) o;
    return Objects.equals(this.pg, inlineResponse20032Settings.pg) &&
        Objects.equals(this.pglookout, inlineResponse20032Settings.pglookout) &&
        Objects.equals(this.pgbouncer, inlineResponse20032Settings.pgbouncer) &&
        Objects.equals(this.timescaledb, inlineResponse20032Settings.timescaledb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pg, pglookout, pgbouncer, timescaledb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20032Settings {\n");
    
    sb.append("    pg: ").append(toIndentedString(pg)).append("\n");
    sb.append("    pglookout: ").append(toIndentedString(pglookout)).append("\n");
    sb.append("    pgbouncer: ").append(toIndentedString(pgbouncer)).append("\n");
    sb.append("    timescaledb: ").append(toIndentedString(timescaledb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
