/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.client.model.BlockStorageSnapshotTarget;
import org.openapitools.client.model.InstanceTarget;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Block storage volume
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-27T17:14:44.205710495Z[Etc/UTC]", comments = "Generator version: 7.5.0-SNAPSHOT")
public class BlockStorageVolume {
  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = new HashMap<>();

  public static final String SERIALIZED_NAME_INSTANCE = "instance";
  @SerializedName(SERIALIZED_NAME_INSTANCE)
  private InstanceTarget instance;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * Volume state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    SNAPSHOTTING("snapshotting"),
    
    DELETED("deleted"),
    
    CREATING("creating"),
    
    DETACHED("detached"),
    
    DELETING("deleting"),
    
    ATTACHING("attaching"),
    
    ERROR("error"),
    
    ATTACHED("attached"),
    
    DETACHING("detaching");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Long size;

  public static final String SERIALIZED_NAME_BLOCKSIZE = "blocksize";
  @SerializedName(SERIALIZED_NAME_BLOCKSIZE)
  private Long blocksize;

  public static final String SERIALIZED_NAME_BLOCK_STORAGE_SNAPSHOTS = "block-storage-snapshots";
  @SerializedName(SERIALIZED_NAME_BLOCK_STORAGE_SNAPSHOTS)
  private List<BlockStorageSnapshotTarget> blockStorageSnapshots = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created-at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public BlockStorageVolume() {
  }

  public BlockStorageVolume(
     StateEnum state, 
     Long blocksize, 
     UUID id, 
     OffsetDateTime createdAt
  ) {
    this();
    this.state = state;
    this.blocksize = blocksize;
    this.id = id;
    this.createdAt = createdAt;
  }

  public BlockStorageVolume labels(Map<String, String> labels) {
    this.labels = labels;
    return this;
  }

  public BlockStorageVolume putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @javax.annotation.Nullable
  public Map<String, String> getLabels() {
    return labels;
  }

  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public BlockStorageVolume instance(InstanceTarget instance) {
    this.instance = instance;
    return this;
  }

   /**
   * Get instance
   * @return instance
  **/
  @javax.annotation.Nullable
  public InstanceTarget getInstance() {
    return instance;
  }

  public void setInstance(InstanceTarget instance) {
    this.instance = instance;
  }


  public BlockStorageVolume name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Volume name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


   /**
   * Volume state
   * @return state
  **/
  @javax.annotation.Nullable
  public StateEnum getState() {
    return state;
  }



  public BlockStorageVolume size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Volume size
   * minimum: 10
   * maximum: 10240
   * @return size
  **/
  @javax.annotation.Nullable
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }


   /**
   * Volume block size
   * minimum: 0
   * @return blocksize
  **/
  @javax.annotation.Nullable
  public Long getBlocksize() {
    return blocksize;
  }



  public BlockStorageVolume blockStorageSnapshots(List<BlockStorageSnapshotTarget> blockStorageSnapshots) {
    this.blockStorageSnapshots = blockStorageSnapshots;
    return this;
  }

  public BlockStorageVolume addBlockStorageSnapshotsItem(BlockStorageSnapshotTarget blockStorageSnapshotsItem) {
    if (this.blockStorageSnapshots == null) {
      this.blockStorageSnapshots = new ArrayList<>();
    }
    this.blockStorageSnapshots.add(blockStorageSnapshotsItem);
    return this;
  }

   /**
   * Volume snapshots, if any
   * @return blockStorageSnapshots
  **/
  @javax.annotation.Nullable
  public List<BlockStorageSnapshotTarget> getBlockStorageSnapshots() {
    return blockStorageSnapshots;
  }

  public void setBlockStorageSnapshots(List<BlockStorageSnapshotTarget> blockStorageSnapshots) {
    this.blockStorageSnapshots = blockStorageSnapshots;
  }


   /**
   * Volume ID
   * @return id
  **/
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }



   /**
   * Volume creation date
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockStorageVolume blockStorageVolume = (BlockStorageVolume) o;
    return Objects.equals(this.labels, blockStorageVolume.labels) &&
        Objects.equals(this.instance, blockStorageVolume.instance) &&
        Objects.equals(this.name, blockStorageVolume.name) &&
        Objects.equals(this.state, blockStorageVolume.state) &&
        Objects.equals(this.size, blockStorageVolume.size) &&
        Objects.equals(this.blocksize, blockStorageVolume.blocksize) &&
        Objects.equals(this.blockStorageSnapshots, blockStorageVolume.blockStorageSnapshots) &&
        Objects.equals(this.id, blockStorageVolume.id) &&
        Objects.equals(this.createdAt, blockStorageVolume.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, instance, name, state, size, blocksize, blockStorageSnapshots, id, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockStorageVolume {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    blocksize: ").append(toIndentedString(blocksize)).append("\n");
    sb.append("    blockStorageSnapshots: ").append(toIndentedString(blockStorageSnapshots)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("labels");
    openapiFields.add("instance");
    openapiFields.add("name");
    openapiFields.add("state");
    openapiFields.add("size");
    openapiFields.add("blocksize");
    openapiFields.add("block-storage-snapshots");
    openapiFields.add("id");
    openapiFields.add("created-at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BlockStorageVolume
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BlockStorageVolume.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BlockStorageVolume is not found in the empty JSON string", BlockStorageVolume.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BlockStorageVolume.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BlockStorageVolume` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `instance`
      if (jsonObj.get("instance") != null && !jsonObj.get("instance").isJsonNull()) {
        InstanceTarget.validateJsonElement(jsonObj.get("instance"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        StateEnum.validateJsonElement(jsonObj.get("state"));
      }
      if (jsonObj.get("block-storage-snapshots") != null && !jsonObj.get("block-storage-snapshots").isJsonNull()) {
        JsonArray jsonArrayblockStorageSnapshots = jsonObj.getAsJsonArray("block-storage-snapshots");
        if (jsonArrayblockStorageSnapshots != null) {
          // ensure the json data is an array
          if (!jsonObj.get("block-storage-snapshots").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `block-storage-snapshots` to be an array in the JSON string but got `%s`", jsonObj.get("block-storage-snapshots").toString()));
          }

          // validate the optional field `block-storage-snapshots` (array)
          for (int i = 0; i < jsonArrayblockStorageSnapshots.size(); i++) {
            BlockStorageSnapshotTarget.validateJsonElement(jsonArrayblockStorageSnapshots.get(i));
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BlockStorageVolume.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BlockStorageVolume' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BlockStorageVolume> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BlockStorageVolume.class));

       return (TypeAdapter<T>) new TypeAdapter<BlockStorageVolume>() {
           @Override
           public void write(JsonWriter out, BlockStorageVolume value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BlockStorageVolume read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BlockStorageVolume given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BlockStorageVolume
  * @throws IOException if the JSON string is invalid with respect to BlockStorageVolume
  */
  public static BlockStorageVolume fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BlockStorageVolume.class);
  }

 /**
  * Convert an instance of BlockStorageVolume to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

