/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OpensearchEmailSenderSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-27T17:14:44.205710495Z[Etc/UTC]", comments = "Generator version: 7.5.0-SNAPSHOT")
public class OpensearchEmailSenderSettings {
  public static final String SERIALIZED_NAME_EMAIL_SENDER_NAME = "email_sender_name";
  @SerializedName(SERIALIZED_NAME_EMAIL_SENDER_NAME)
  private String emailSenderName;

  public static final String SERIALIZED_NAME_EMAIL_SENDER_PASSWORD = "email_sender_password";
  @SerializedName(SERIALIZED_NAME_EMAIL_SENDER_PASSWORD)
  private String emailSenderPassword;

  public static final String SERIALIZED_NAME_EMAIL_SENDER_USERNAME = "email_sender_username";
  @SerializedName(SERIALIZED_NAME_EMAIL_SENDER_USERNAME)
  private String emailSenderUsername;

  public OpensearchEmailSenderSettings() {
  }

  public OpensearchEmailSenderSettings emailSenderName(String emailSenderName) {
    this.emailSenderName = emailSenderName;
    return this;
  }

   /**
   * This should be identical to the Sender name defined in Opensearch dashboards
   * @return emailSenderName
  **/
  @javax.annotation.Nonnull
  public String getEmailSenderName() {
    return emailSenderName;
  }

  public void setEmailSenderName(String emailSenderName) {
    this.emailSenderName = emailSenderName;
  }


  public OpensearchEmailSenderSettings emailSenderPassword(String emailSenderPassword) {
    this.emailSenderPassword = emailSenderPassword;
    return this;
  }

   /**
   * Sender password for Opensearch alerts to authenticate with SMTP server
   * @return emailSenderPassword
  **/
  @javax.annotation.Nonnull
  public String getEmailSenderPassword() {
    return emailSenderPassword;
  }

  public void setEmailSenderPassword(String emailSenderPassword) {
    this.emailSenderPassword = emailSenderPassword;
  }


  public OpensearchEmailSenderSettings emailSenderUsername(String emailSenderUsername) {
    this.emailSenderUsername = emailSenderUsername;
    return this;
  }

   /**
   * Get emailSenderUsername
   * @return emailSenderUsername
  **/
  @javax.annotation.Nonnull
  public String getEmailSenderUsername() {
    return emailSenderUsername;
  }

  public void setEmailSenderUsername(String emailSenderUsername) {
    this.emailSenderUsername = emailSenderUsername;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpensearchEmailSenderSettings opensearchEmailSenderSettings = (OpensearchEmailSenderSettings) o;
    return Objects.equals(this.emailSenderName, opensearchEmailSenderSettings.emailSenderName) &&
        Objects.equals(this.emailSenderPassword, opensearchEmailSenderSettings.emailSenderPassword) &&
        Objects.equals(this.emailSenderUsername, opensearchEmailSenderSettings.emailSenderUsername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailSenderName, emailSenderPassword, emailSenderUsername);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpensearchEmailSenderSettings {\n");
    sb.append("    emailSenderName: ").append(toIndentedString(emailSenderName)).append("\n");
    sb.append("    emailSenderPassword: ").append(toIndentedString(emailSenderPassword)).append("\n");
    sb.append("    emailSenderUsername: ").append(toIndentedString(emailSenderUsername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("email_sender_name");
    openapiFields.add("email_sender_password");
    openapiFields.add("email_sender_username");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("email_sender_name");
    openapiRequiredFields.add("email_sender_password");
    openapiRequiredFields.add("email_sender_username");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OpensearchEmailSenderSettings
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpensearchEmailSenderSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpensearchEmailSenderSettings is not found in the empty JSON string", OpensearchEmailSenderSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpensearchEmailSenderSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpensearchEmailSenderSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OpensearchEmailSenderSettings.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("email_sender_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email_sender_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_sender_name").toString()));
      }
      if (!jsonObj.get("email_sender_password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email_sender_password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_sender_password").toString()));
      }
      if (!jsonObj.get("email_sender_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email_sender_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_sender_username").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpensearchEmailSenderSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpensearchEmailSenderSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpensearchEmailSenderSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpensearchEmailSenderSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<OpensearchEmailSenderSettings>() {
           @Override
           public void write(JsonWriter out, OpensearchEmailSenderSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpensearchEmailSenderSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OpensearchEmailSenderSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OpensearchEmailSenderSettings
  * @throws IOException if the JSON string is invalid with respect to OpensearchEmailSenderSettings
  */
  public static OpensearchEmailSenderSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpensearchEmailSenderSettings.class);
  }

 /**
  * Convert an instance of OpensearchEmailSenderSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

