/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.exoscale4j.model;

import com.exoscale.exoscale4j.model.DbaasBackupConfig;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for DbaasPlan
 */
public class DbaasPlanTest {
    private final DbaasPlan model = new DbaasPlan();

    /**
     * Model tests for DbaasPlan
     */
    @Test
    public void testDbaasPlan() {
        // TODO: test DbaasPlan
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodeCount'
     */
    @Test
    public void nodeCountTest() {
        // TODO: test nodeCount
    }

    /**
     * Test the property 'nodeCpuCount'
     */
    @Test
    public void nodeCpuCountTest() {
        // TODO: test nodeCpuCount
    }

    /**
     * Test the property 'diskSpace'
     */
    @Test
    public void diskSpaceTest() {
        // TODO: test diskSpace
    }

    /**
     * Test the property 'nodeMemory'
     */
    @Test
    public void nodeMemoryTest() {
        // TODO: test nodeMemory
    }

    /**
     * Test the property 'maxMemoryPercent'
     */
    @Test
    public void maxMemoryPercentTest() {
        // TODO: test maxMemoryPercent
    }

    /**
     * Test the property 'backupConfig'
     */
    @Test
    public void backupConfigTest() {
        // TODO: test backupConfig
    }

    /**
     * Test the property 'authorized'
     */
    @Test
    public void authorizedTest() {
        // TODO: test authorized
    }

}
