/*
 * Exoscale Public API
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.exoscale.exoscale4j.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EnumMysqlAuthenticationPlugin
 */
public class EnumMysqlAuthenticationPluginTest {
    /**
     * Model tests for EnumMysqlAuthenticationPlugin
     */
    @Test
    public void testEnumMysqlAuthenticationPlugin() {
        // TODO: test EnumMysqlAuthenticationPlugin
    }

}
