/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.components;

import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * DbaasNodeStateState - Current state of the service node
 */
public enum DbaasNodeStateState {
    LEAVING("leaving"),
    RUNNING("running"),
    SYNCING_DATA("syncing_data"),
    SETTING_UP_VM("setting_up_vm"),
    UNKNOWN("unknown");

    @JsonValue
    private final String value;

    private DbaasNodeStateState(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
