/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.exoscale.api.models.components;

import com.exoscale.api.utils.Utils;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

/**
 * SecurityGroupRule - Security Group rule
 */

public class SecurityGroupRule {

    /**
     * Security Group rule description
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<? extends String> description;

    /**
     * Start port of the range
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("start-port")
    private Optional<? extends Long> startPort;

    /**
     * Network protocol
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("protocol")
    private Optional<? extends SecurityGroupRuleProtocol> protocol;

    /**
     * ICMP details
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("icmp")
    private Optional<? extends Icmp> icmp;

    /**
     * End port of the range
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end-port")
    private Optional<? extends Long> endPort;

    /**
     * Security Group
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("security-group")
    private Optional<? extends SecurityGroupResource> securityGroup;

    /**
     * CIDR-formatted network allowed
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("network")
    private Optional<? extends String> network;

    /**
     * Network flow direction to match
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flow-direction")
    private Optional<? extends FlowDirection> flowDirection;

    public SecurityGroupRule(
            @JsonProperty("description") Optional<? extends String> description,
            @JsonProperty("start-port") Optional<? extends Long> startPort,
            @JsonProperty("protocol") Optional<? extends SecurityGroupRuleProtocol> protocol,
            @JsonProperty("icmp") Optional<? extends Icmp> icmp,
            @JsonProperty("end-port") Optional<? extends Long> endPort,
            @JsonProperty("security-group") Optional<? extends SecurityGroupResource> securityGroup,
            @JsonProperty("network") Optional<? extends String> network,
            @JsonProperty("flow-direction") Optional<? extends FlowDirection> flowDirection) {
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(startPort, "startPort");
        Utils.checkNotNull(protocol, "protocol");
        Utils.checkNotNull(icmp, "icmp");
        Utils.checkNotNull(endPort, "endPort");
        Utils.checkNotNull(securityGroup, "securityGroup");
        Utils.checkNotNull(network, "network");
        Utils.checkNotNull(flowDirection, "flowDirection");
        this.description = description;
        this.startPort = startPort;
        this.protocol = protocol;
        this.icmp = icmp;
        this.endPort = endPort;
        this.securityGroup = securityGroup;
        this.network = network;
        this.flowDirection = flowDirection;
    }

    /**
     * Security Group rule description
     */
    public Optional<? extends String> description() {
        return description;
    }

    /**
     * Start port of the range
     */
    public Optional<? extends Long> startPort() {
        return startPort;
    }

    /**
     * Network protocol
     */
    public Optional<? extends SecurityGroupRuleProtocol> protocol() {
        return protocol;
    }

    /**
     * ICMP details
     */
    public Optional<? extends Icmp> icmp() {
        return icmp;
    }

    /**
     * End port of the range
     */
    public Optional<? extends Long> endPort() {
        return endPort;
    }

    /**
     * Security Group
     */
    public Optional<? extends SecurityGroupResource> securityGroup() {
        return securityGroup;
    }

    /**
     * CIDR-formatted network allowed
     */
    public Optional<? extends String> network() {
        return network;
    }

    /**
     * Network flow direction to match
     */
    public Optional<? extends FlowDirection> flowDirection() {
        return flowDirection;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Security Group rule description
     */
    public SecurityGroupRule withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }

    /**
     * Security Group rule description
     */
    public SecurityGroupRule withDescription(Optional<? extends String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * Start port of the range
     */
    public SecurityGroupRule withStartPort(long startPort) {
        Utils.checkNotNull(startPort, "startPort");
        this.startPort = Optional.ofNullable(startPort);
        return this;
    }

    /**
     * Start port of the range
     */
    public SecurityGroupRule withStartPort(Optional<? extends Long> startPort) {
        Utils.checkNotNull(startPort, "startPort");
        this.startPort = startPort;
        return this;
    }

    /**
     * Network protocol
     */
    public SecurityGroupRule withProtocol(SecurityGroupRuleProtocol protocol) {
        Utils.checkNotNull(protocol, "protocol");
        this.protocol = Optional.ofNullable(protocol);
        return this;
    }

    /**
     * Network protocol
     */
    public SecurityGroupRule withProtocol(Optional<? extends SecurityGroupRuleProtocol> protocol) {
        Utils.checkNotNull(protocol, "protocol");
        this.protocol = protocol;
        return this;
    }

    /**
     * ICMP details
     */
    public SecurityGroupRule withIcmp(Icmp icmp) {
        Utils.checkNotNull(icmp, "icmp");
        this.icmp = Optional.ofNullable(icmp);
        return this;
    }

    /**
     * ICMP details
     */
    public SecurityGroupRule withIcmp(Optional<? extends Icmp> icmp) {
        Utils.checkNotNull(icmp, "icmp");
        this.icmp = icmp;
        return this;
    }

    /**
     * End port of the range
     */
    public SecurityGroupRule withEndPort(long endPort) {
        Utils.checkNotNull(endPort, "endPort");
        this.endPort = Optional.ofNullable(endPort);
        return this;
    }

    /**
     * End port of the range
     */
    public SecurityGroupRule withEndPort(Optional<? extends Long> endPort) {
        Utils.checkNotNull(endPort, "endPort");
        this.endPort = endPort;
        return this;
    }

    /**
     * Security Group
     */
    public SecurityGroupRule withSecurityGroup(SecurityGroupResource securityGroup) {
        Utils.checkNotNull(securityGroup, "securityGroup");
        this.securityGroup = Optional.ofNullable(securityGroup);
        return this;
    }

    /**
     * Security Group
     */
    public SecurityGroupRule withSecurityGroup(Optional<? extends SecurityGroupResource> securityGroup) {
        Utils.checkNotNull(securityGroup, "securityGroup");
        this.securityGroup = securityGroup;
        return this;
    }

    /**
     * CIDR-formatted network allowed
     */
    public SecurityGroupRule withNetwork(String network) {
        Utils.checkNotNull(network, "network");
        this.network = Optional.ofNullable(network);
        return this;
    }

    /**
     * CIDR-formatted network allowed
     */
    public SecurityGroupRule withNetwork(Optional<? extends String> network) {
        Utils.checkNotNull(network, "network");
        this.network = network;
        return this;
    }

    /**
     * Network flow direction to match
     */
    public SecurityGroupRule withFlowDirection(FlowDirection flowDirection) {
        Utils.checkNotNull(flowDirection, "flowDirection");
        this.flowDirection = Optional.ofNullable(flowDirection);
        return this;
    }

    /**
     * Network flow direction to match
     */
    public SecurityGroupRule withFlowDirection(Optional<? extends FlowDirection> flowDirection) {
        Utils.checkNotNull(flowDirection, "flowDirection");
        this.flowDirection = flowDirection;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SecurityGroupRule other = (SecurityGroupRule) o;
        return 
            java.util.Objects.deepEquals(this.description, other.description) &&
            java.util.Objects.deepEquals(this.startPort, other.startPort) &&
            java.util.Objects.deepEquals(this.protocol, other.protocol) &&
            java.util.Objects.deepEquals(this.icmp, other.icmp) &&
            java.util.Objects.deepEquals(this.endPort, other.endPort) &&
            java.util.Objects.deepEquals(this.securityGroup, other.securityGroup) &&
            java.util.Objects.deepEquals(this.network, other.network) &&
            java.util.Objects.deepEquals(this.flowDirection, other.flowDirection);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            description,
            startPort,
            protocol,
            icmp,
            endPort,
            securityGroup,
            network,
            flowDirection);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SecurityGroupRule.class,
                "description", description,
                "startPort", startPort,
                "protocol", protocol,
                "icmp", icmp,
                "endPort", endPort,
                "securityGroup", securityGroup,
                "network", network,
                "flowDirection", flowDirection);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> description = Optional.empty();
 
        private Optional<? extends Long> startPort = Optional.empty();
 
        private Optional<? extends SecurityGroupRuleProtocol> protocol = Optional.empty();
 
        private Optional<? extends Icmp> icmp = Optional.empty();
 
        private Optional<? extends Long> endPort = Optional.empty();
 
        private Optional<? extends SecurityGroupResource> securityGroup = Optional.empty();
 
        private Optional<? extends String> network = Optional.empty();
 
        private Optional<? extends FlowDirection> flowDirection = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Security Group rule description
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * Security Group rule description
         */
        public Builder description(Optional<? extends String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        /**
         * Start port of the range
         */
        public Builder startPort(long startPort) {
            Utils.checkNotNull(startPort, "startPort");
            this.startPort = Optional.ofNullable(startPort);
            return this;
        }

        /**
         * Start port of the range
         */
        public Builder startPort(Optional<? extends Long> startPort) {
            Utils.checkNotNull(startPort, "startPort");
            this.startPort = startPort;
            return this;
        }

        /**
         * Network protocol
         */
        public Builder protocol(SecurityGroupRuleProtocol protocol) {
            Utils.checkNotNull(protocol, "protocol");
            this.protocol = Optional.ofNullable(protocol);
            return this;
        }

        /**
         * Network protocol
         */
        public Builder protocol(Optional<? extends SecurityGroupRuleProtocol> protocol) {
            Utils.checkNotNull(protocol, "protocol");
            this.protocol = protocol;
            return this;
        }

        /**
         * ICMP details
         */
        public Builder icmp(Icmp icmp) {
            Utils.checkNotNull(icmp, "icmp");
            this.icmp = Optional.ofNullable(icmp);
            return this;
        }

        /**
         * ICMP details
         */
        public Builder icmp(Optional<? extends Icmp> icmp) {
            Utils.checkNotNull(icmp, "icmp");
            this.icmp = icmp;
            return this;
        }

        /**
         * End port of the range
         */
        public Builder endPort(long endPort) {
            Utils.checkNotNull(endPort, "endPort");
            this.endPort = Optional.ofNullable(endPort);
            return this;
        }

        /**
         * End port of the range
         */
        public Builder endPort(Optional<? extends Long> endPort) {
            Utils.checkNotNull(endPort, "endPort");
            this.endPort = endPort;
            return this;
        }

        /**
         * Security Group
         */
        public Builder securityGroup(SecurityGroupResource securityGroup) {
            Utils.checkNotNull(securityGroup, "securityGroup");
            this.securityGroup = Optional.ofNullable(securityGroup);
            return this;
        }

        /**
         * Security Group
         */
        public Builder securityGroup(Optional<? extends SecurityGroupResource> securityGroup) {
            Utils.checkNotNull(securityGroup, "securityGroup");
            this.securityGroup = securityGroup;
            return this;
        }

        /**
         * CIDR-formatted network allowed
         */
        public Builder network(String network) {
            Utils.checkNotNull(network, "network");
            this.network = Optional.ofNullable(network);
            return this;
        }

        /**
         * CIDR-formatted network allowed
         */
        public Builder network(Optional<? extends String> network) {
            Utils.checkNotNull(network, "network");
            this.network = network;
            return this;
        }

        /**
         * Network flow direction to match
         */
        public Builder flowDirection(FlowDirection flowDirection) {
            Utils.checkNotNull(flowDirection, "flowDirection");
            this.flowDirection = Optional.ofNullable(flowDirection);
            return this;
        }

        /**
         * Network flow direction to match
         */
        public Builder flowDirection(Optional<? extends FlowDirection> flowDirection) {
            Utils.checkNotNull(flowDirection, "flowDirection");
            this.flowDirection = flowDirection;
            return this;
        }
        
        public SecurityGroupRule build() {
            return new SecurityGroupRule(
                description,
                startPort,
                protocol,
                icmp,
                endPort,
                securityGroup,
                network,
                flowDirection);
        }
    }
}

