name: Update OpenAPI and generate SDK

on:
  push:
    branches:
      - actions-test

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Fetch latest OpenAPI definition
        shell: bash
        run: |-
          curl -s https://openapi-v2.exoscale.com/source.yaml -o sdk/api/openapi.yaml
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add sdk/api/openapi.yaml
          timestamp=$(date -u)
          git commit -m "OpenAPI spec update: ${timestamp}" || exit 0
          git push origin actions-test  # Change to main branch after testing
