name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: 'central' 
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    
    # Import GPG key
    - name: Import GPG key
      run: |
        echo "${{ secrets.MAVEN_GPG_KEYRING }}" | gpg --dearmor > ~/my_secring.gpg
        gpg --batch --yes --import ~/my_secring.gpg
        
    - name: Generate settings.xml
      run: |
        cat << EOF > ${{ github.workspace }}/settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>central</id>
              <username>${{ secrets.MAVEN_USERNAME }}</username>
              <password>${{ secrets.MAVEN_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
            <id>gpg</id>
            <properties>
              <gpg.executable>gpg</gpg.executable>
              <gpg.keyname>${{ secrets.MAVEN_GPG_KEYNAME }}</gpg.keyname>
              <gpg.passphrase>${{ secrets.MAVEN_GPG_PASSPHRAS }}</gpg.passphrase>
            </properties>
          </profile>
        </profiles>
        <activeProfiles>
          <activeProfile>gpg</activeProfile>
          </activeProfiles>
        </settings>
        EOF


    # Build with Maven
    - name: Build with Maven
      run: mvn -B package --file sdk/pom.xml -s ${{ github.workspace }}/settings.xml -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Psign-artifacts

    # Publish to Maven Central
    - name: Publish to Maven Central
      run: mvn deploy --file sdk/pom.xml -s ${{ github.workspace }}/settings.xml -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Psign-artifacts
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


